### ISSUE TITLE
Error 

### ISSUE THREAD

**Issue by ABarrosoG** [openhab/openhab-mycroft#69]
Mycroft mounted:
Raspberry pi 3 B+
`Distributor ID: Raspbian
Description:    Raspbian GNU/Linux 9.8 (stretch)
Release:        9.8
Codename:       stretch
`
Version Mycroft core:
mycroft-core 19.2.14 

Code error:
`Traceback (most recent call last):
  File "/home/pi/mycroft-core/mycroft/skills/core.py", line 1093, in wrapper
    handler(message)
  File "/opt/mycroft/skills/openhab-skill.openhab/__init__.py", line 175, in handle_refresh_tagged_items_intent
    self.speak_dialog('RefreshTaggedItems', {'number_item': dictLenght})
  File "/home/pi/mycroft-core/mycroft/skills/core.py", line 1439, in speak_dialog
    self.speak(self.dialog_renderer.render(key, data),
  File "/home/pi/mycroft-core/mycroft/dialog/__init__.py", line 93, in render
    line = line.format(**context)
KeyError: 'number_items'
`

**Comment by mortommy** [comment]
Fixed. Could you try now?
Thank you

**Comment by ABarrosoG** [comment]
Fixed. 
Thanks!
